services:
  redis-master:
    container_name: redis-master
    image: redis:7.2.5
    command: ["redis-server", "--appendonly", "yes", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network

  redis-slave1:
    container_name: redis-slave1
    image: redis:7.2.5
    command:
      - redis-server
      - --replicaof
      - redis-master
      - "6379"
      - --bind
      - "0.0.0.0"
    ports:
      - "6380:6379"
    volumes:
      - redis-slave1-data:/data
    networks:
      - redis-network

  redis-slave2:
    container_name: redis-slave2
    image: redis:7.2.5
    command:
      - redis-server
      - --replicaof
      - redis-master
      - "6379"
      - --bind
      - "0.0.0.0"
    ports:
      - "6381:6379"
    volumes:
      - redis-slave2-data:/data
    networks:
      - redis-network

  redis-sentinel1:
    container_name: redis-sentinel1
    image: redis:7.2.5
    command: ["redis-server", "/sentinel/sentinel1.conf", "--sentinel"]
    volumes:
      - ./sentinel:/sentinel
    ports:
      - "26379:26379"
    networks:
      - redis-network
    depends_on:
      - redis-master 
      
  redis-sentinel2:
    container_name: redis-sentinel2
    image: redis:7.2.5
    command: ["redis-server", "/sentinel/sentinel2.conf", "--sentinel"]
    volumes:
      - ./sentinel:/sentinel
    ports:
      - "26380:26379"
    networks:
      - redis-network
    depends_on:
      - redis-master 

  redis-sentinel3:
    container_name: redis-sentinel3
    image: redis:7.2.5
    command: ["redis-server", "/sentinel/sentinel3.conf", "--sentinel"]
    volumes:
      - ./sentinel:/sentinel
    ports:
      - "26381:26379"
    networks:
      - redis-network
    depends_on:
      - redis-master      

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-master-data:
  redis-slave1-data:
  redis-slave2-data:
